// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	"github.com/Golang-Turkiye/refactoring-roadmap/internal/urlshorter/domain"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockLinkRepository is an autogenerated mock type for the LinkRepository type
type MockLinkRepository struct {
	mock.Mock
}

// CreateLink provides a mock function with given fields: link
func (_m *MockLinkRepository) CreateLink(link *domain.Link) error {
	ret := _m.Called(link)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Link) error); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeactivateLink provides a mock function with given fields: link
func (_m *MockLinkRepository) DeactivateLink(link *domain.Link) error {
	ret := _m.Called(link)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Link) error); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLinkByID provides a mock function with given fields: linkID
func (_m *MockLinkRepository) GetLinkByID(linkID uint) (*domain.Link, error) {
	ret := _m.Called(linkID)

	var r0 *domain.Link
	if rf, ok := ret.Get(0).(func(uint) *domain.Link); ok {
		r0 = rf(linkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(linkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLinkByURL provides a mock function with given fields: url
func (_m *MockLinkRepository) GetLinkByURL(url string) (*domain.Link, error) {
	ret := _m.Called(url)

	var r0 *domain.Link
	if rf, ok := ret.Get(0).(func(string) *domain.Link); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLinksByUserID provides a mock function with given fields: userID
func (_m *MockLinkRepository) GetLinksByUserID(userID uint) ([]*domain.Link, error) {
	ret := _m.Called(userID)

	var r0 []*domain.Link
	if rf, ok := ret.Get(0).(func(uint) []*domain.Link); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockLinkRepository creates a new instance of MockLinkRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockLinkRepository(t testing.TB) *MockLinkRepository {
	mock := &MockLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
